### ISSUE TITLE
Dictionary: HashMap<BaseWord, Set<ID_Article>>

### ISSUE THREAD

**Issue by discoleo** [Alex-Gombos/SaxParser#1]
# Dictionary with Word occurrences in Articles

Instead of: HashMap<String, Pair<List<String>, Integer>>

Use as a value a Set<Integer> to store the IDs of Articles:
> // HashMap<BaseWord, Set<ID_Article>>\
> HashMap<String, Set<Integer>> mapWords = new HashMap<>();

Alternatively, store the IDs in a Vector<Integer>: this will include also duplicates.

**Comment by Alex-Gombos** [comment]
Added a new method called countWordsNew in WikipediaReader that uses HashMap<BaseWord, Set<ID_Article>>. Also method findWordsInWiktionary now also removes duplicate words from every article
